<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->get('/', 'Home::index', ['filter' => 'sessionauth']);
$routes->get('login', 'Auth::login');
$routes->post('login', 'Auth::authenticate');
$routes->get('mfa', 'Auth::mfa');
$routes->post('mfa', 'Auth::confirm');
$routes->post('login/cancel-mfa', 'Auth::cancelMfa');
$routes->post('login/reset-mfa', 'Auth::resetMfa');
$routes->post('logout', 'Auth::logout', ['filter' => 'sessionauth']);
$routes->get('access/users', 'Access::users', ['filter' => 'sessionauth']);
$routes->post('access/users', 'Access::storeUser', ['filter' => 'sessionauth']);
$routes->post('access/users/sync-hris', 'Access::syncUserHris', ['filter' => 'sessionauth']);
$routes->post('access/users/reset-mfa', 'Access::resetUserMfa', ['filter' => 'sessionauth']);
$routes->post('access/users/toggle-mfa', 'Access::toggleUserMfa', ['filter' => 'sessionauth']);
$routes->post('access/users/(:num)', 'Access::updateUser/$1', ['filter' => 'sessionauth']);
$routes->get('access/job-groups', 'Access::jobGroups', ['filter' => 'sessionauth']);
$routes->post('access/job-groups', 'Access::storeJobGroup', ['filter' => 'sessionauth']);
$routes->post('access/job-groups/sync', 'Access::syncJobGroups', ['filter' => 'sessionauth']);
$routes->post('access/job-groups/(:num)', 'Access::updateJobGroup/$1', ['filter' => 'sessionauth']);
$routes->get('access/roles', 'Access::roles', ['filter' => 'sessionauth']);
$routes->post('access/roles', 'Access::storeRole', ['filter' => 'sessionauth']);
$routes->get('access/roles/(:num)', 'Access::editRole/$1', ['filter' => 'sessionauth']);
$routes->post('access/roles/(:num)', 'Access::updateRole/$1', ['filter' => 'sessionauth']);
$routes->post('access/roles/(:num)/permissions', 'Access::savePermissions/$1', ['filter' => 'sessionauth']);
$routes->get('access/permissions', 'Access::permissions', ['filter' => 'sessionauth']);
$routes->get('master/branches', 'Master::branches', ['filter' => 'sessionauth']);
$routes->post('master/branches', 'Master::storeBranch', ['filter' => 'sessionauth']);
$routes->post('master/branches/sync', 'Master::syncBranches', ['filter' => 'sessionauth']);
$routes->post('master/branches/(:num)', 'Master::updateBranch/$1', ['filter' => 'sessionauth']);
$routes->get('master/products/datatables', 'Master::productsDatatables', ['filter' => 'sessionauth']);
$routes->get('master/products', 'Master::products', ['filter' => 'sessionauth']);
$routes->post('master/products', 'Master::storeProduct', ['filter' => 'sessionauth']);
$routes->post('master/products/(:num)', 'Master::updateProduct/$1', ['filter' => 'sessionauth']);
$routes->get('master/debtors', 'Master::debtors', ['filter' => 'sessionauth']);
$routes->get('master/debtors/next-cis-id', 'Master::nextCisId', ['filter' => 'sessionauth']);
$routes->get('master/debtors/inquiry-cif/(:any)', 'Master::inquiryCif/$1', ['filter' => 'sessionauth']);
$routes->post('master/debtors', 'Master::storeDebtor', ['filter' => 'sessionauth']);
$routes->post('master/debtors/(:num)', 'Master::updateDebtor/$1', ['filter' => 'sessionauth']);
$routes->post('master/debtors/import', 'Master::importDebtors', ['filter' => 'sessionauth']);
$routes->get('scoring/parameters', 'ScoringConfig::parameters', ['filter' => 'sessionauth']);
$routes->post('scoring/parameters/store', 'ScoringConfig::storeMasterParameter', ['filter' => 'sessionauth']);
$routes->post('scoring/parameters/(:num)/update', 'ScoringConfig::updateMasterParameter/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/parameters/(:num)/delete', 'ScoringConfig::deleteMasterParameter/$1', ['filter' => 'sessionauth']);
$routes->get('scoring/mapping', 'ScoringConfig::mapping', ['filter' => 'sessionauth']);
$routes->post('scoring/mapping/store', 'ScoringConfig::storeMapping', ['filter' => 'sessionauth']);
$routes->post('scoring/mapping/upload', 'ScoringConfig::uploadMappingAttachment', ['filter' => 'sessionauth']);
$routes->get('scoring/mapping/(:num)', 'ScoringConfig::mappingDetail/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/mapping/(:num)/update', 'ScoringConfig::updateMapping/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/mapping/(:num)/delete', 'ScoringConfig::deleteMapping/$1', ['filter' => 'sessionauth']);
$routes->get('scoring/credit', 'ScoringConfig::creditScoring', ['filter' => 'sessionauth']);
$routes->get('scoring/credit/check-duplicate', 'ScoringConfig::checkDuplicate', ['filter' => 'sessionauth']);
$routes->get('scoring/credit/debtor-history/(:num)', 'ScoringConfig::debtorHistory/$1', ['filter' => 'sessionauth']);
$routes->get('scoring/credit/mapping-items/(:num)', 'ScoringConfig::creditMappingItems/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/credit/save', 'ScoringConfig::saveCreditScoring', ['filter' => 'sessionauth']);

$routes->get('scoring/products', 'ScoringConfig::products', ['filter' => 'sessionauth']);
$routes->get('scoring/products/(:num)', 'ScoringConfig::versions/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/products/(:num)/versions', 'ScoringConfig::createVersion/$1', ['filter' => 'sessionauth']);
$routes->get('scoring/versions/(:num)', 'ScoringConfig::show/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/versions/(:num)/parameters', 'ScoringConfig::storeParameter/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/parameters/(:num)/options', 'ScoringConfig::storeOption/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/versions/(:num)/thresholds', 'ScoringConfig::storeThreshold/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/versions/(:num)/fields', 'ScoringConfig::storeField/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/fields/(:num)/options', 'ScoringConfig::storeFieldOption/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/versions/(:num)/activate', 'ScoringConfig::activate/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/versions/(:num)/copy', 'ScoringConfig::copyVersion/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/versions/(:num)/calculate', 'ScoringConfig::calculate/$1', ['filter' => 'sessionauth']);
$routes->get('transactions', 'Transactions::index', ['filter' => 'sessionauth']);
$routes->get('transactions/new', 'Transactions::start', ['filter' => 'sessionauth']);
$routes->post('transactions', 'Transactions::create', ['filter' => 'sessionauth']);
$routes->get('transactions/(:num)', 'Transactions::input', ['filter' => 'sessionauth']);
$routes->post('transactions/(:num)/answers', 'Transactions::save', ['filter' => 'sessionauth']);
$routes->get('transactions/(:num)/review', 'Transactions::review', ['filter' => 'sessionauth']);
$routes->post('transactions/(:num)/submit', 'Transactions::submit', ['filter' => 'sessionauth']);
$routes->get('approvals', 'Approvals::index', ['filter' => 'sessionauth']);
$routes->get('approvals/(:num)', 'Approvals::show/$1', ['filter' => 'sessionauth']);
$routes->post('approvals/(:num)/assign', 'Approvals::assign/$1', ['filter' => 'sessionauth']);
$routes->post('approvals/(:num)/decide', 'Approvals::decide/$1', ['filter' => 'sessionauth']);
$routes->post('approvals/duplicate/(:num)/approve', 'Approvals::duplicateApprove/$1', ['filter' => 'sessionauth']);
$routes->post('approvals/duplicate/(:num)/reject', 'Approvals::duplicateReject/$1', ['filter' => 'sessionauth']);
$routes->get('rescore', 'Rescore::index', ['filter' => 'sessionauth']);
$routes->post('rescore', 'Rescore::create', ['filter' => 'sessionauth']);
$routes->post('rescore/(:num)/approve', 'Rescore::approve/$1', ['filter' => 'sessionauth']);
$routes->post('transactions/(:num)/duplicate', 'Transactions::duplicate/$1', ['filter' => 'sessionauth']);
$routes->post('scoring/duplicate-setting', 'ScoringConfig::duplicateSetting', ['filter' => 'sessionauth']);
$routes->post('scoring/passing-score-setting', 'ScoringConfig::passingScoreSetting', ['filter' => 'sessionauth']);
$routes->get('reports/scoring/datatables', 'Reports::scoringDatatables', ['filter' => 'sessionauth']);
$routes->get('reports/scoring', 'Reports::scoring', ['filter' => 'sessionauth']);
$routes->get('reports/debtors/(:num)/datatables', 'Reports::debtorsDatatables/$1', ['filter' => 'sessionauth']);
$routes->get('reports/debtors', 'Reports::debtors', ['filter' => 'sessionauth']);
$routes->get('reports/products', 'Reports::products', ['filter' => 'sessionauth']);
$routes->get('reports/changes/datatables', 'Reports::changesDatatables', ['filter' => 'sessionauth']);
$routes->get('reports/changes', 'Reports::changes', ['filter' => 'sessionauth']);
$routes->get('audit/datatables', 'AuditTrail::datatables', ['filter' => 'sessionauth']);
$routes->get('audit/detail/(:num)', 'AuditTrail::detail/$1', ['filter' => 'sessionauth']);
$routes->get('audit', 'AuditTrail::index', ['filter' => 'sessionauth']);

$routes->get('notifications', 'Notifications::index', ['filter' => 'sessionauth']);
$routes->post('notifications/(:num)/read', 'Notifications::read/$1', ['filter' => 'sessionauth']);
